### ISSUE TITLE
Issue with creating a new  Nx workspace “Failed to install depended”

### ISSUE THREAD

**Issue by brianstittsr** [jpbarbosa/neo4j-crud#1]
Hi JP,

I’m new to Nx and monorepos. When I try to create a new workspace it gives an error “Failure to install dependencies.  I have no idea what to do. I have upgraded Node and npm to the latest versions but I continue to get the same error. Attached is a screenshot of the error.
![IMG_9641](https://github.com/jpbarbosa/neo4j-crud/assets/23502868/c4f32710-e33c-4630-a0e9-7d62353f81eb)

**Comment by jpbarbosa** [comment]
Hey Brian,

I've just double checked that its working for me (attached screenshot).

Which Node version are running on? Please make sure to use 20.11.x 

```bash
$ node --version
v20.11.1
``` 

<img width="711" alt="image" src="https://github.com/jpbarbosa/neo4j-crud/assets/2099381/224f0779-96cf-446e-b49f-8069c85916f6">

**Comment by brianstittsr** [comment]
Here’s the current output:



***@***.*** GitHub % node --version
v20.11.1
***@***.*** GitHub % npx ***@***.*** neo4j-crud --preset=ts


 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Set up CI with caching, distribution and test deflaking · skip
✔ Would you like remote caching to make your build faster? · yes

 >  NX   Creating your v18.0.4 workspace.

✖ Installing dependencies with npm

 >  NX   Failed to install dependencies

   Error:



Thanks,

Brian Stitt Sr.
***@***.***
919-608-3415

**Comment by jpbarbosa** [comment]
Please, give another try answering SKIP on "Would you like remote caching to make your build faster?"

**Comment by brianstittsr** [comment]
Here's the error from the log file output:

/private/var/folders/bn/bp7g34hd6n71ynqnt90thc000000gn/T/tmp-53343-j4BmDxb4jI78/node_modules/nx/node_modules/yargs-parser/build/index.cjs:1
se if (configuration['halt-at-non-option']) {
   ^^

SyntaxError: Unexpected token 'if'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/private/var/folders/bn/bp7g34hd6n71ynqnt90thc000000gn/T/tmp-53343-j4BmDxb4jI78/node_modules/nx/node_modules/yargs/build/index.cjs:1:60570)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)

Node.js v20.11.1

**Comment by brianstittsr** [comment]
Here's what happens when just create the Nx workspace and allow the wizard to prompt for choices:

brianstitt@MacBook-Pro-2 GitHub % npx create-nx-workspace


 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · NEO4JCRUD
✔ Which stack do you want to use? · none
✔ Package-based monorepo, integrated monorepo, or standalone project? · package-based
✔ Do you want Nx Cloud to make your CI fast? · skip

 >  NX   Creating your v18.0.4 workspace.

✖ Installing dependencies with npm

 >  NX   Failed to install dependencies

   Error:

**Comment by brianstittsr** [comment]
Here's my version of NPM: 

brianstitt@MacBook-Pro-2 GitHub % npm --version
10.2.4

**Comment by brianstittsr** [comment]
I just upgraded npm to latest version 

brianstitt@MacBook-Pro-2 GitHub % npm --version
10.4.0

**Comment by jpbarbosa** [comment]
This is very unusual, and I believe it is somehow an issue with your environment. Try to start a simple Node.js application to check your environment. Further questions on starting an NX application can be easily found at https://nx.dev/getting-started/intro. After you get it working, I will be available to assist you!

**Comment by brianstittsr** [comment]
Hi JP,
I just solved the dependency issue.  I removed node and nvm.  Reinstalled Node and npm. I think the issue was that NPM was out of date which probably caused the depenency installation failure.

**Comment by jpbarbosa** [comment]
Hi Brian. Thank you for letting me know you've got your environment fixed. I'm closing this issue, but feel free to open new ones on any other roadblocks you might face.
